### ISSUE TITLE
Not getting results anymore

### ISSUE THREAD

**Issue by fightveryexplosion** [HermanFassett/youtube-scrape#18]
Hello, as of this morning I am no longer getting results through youtube-scrape.
I tried the example URL from the readme here on GitHub, but it has stopped returning results as well.
In another project of mine I noticed a lot of YouTube changes about a week ago, maybe there have been more changes that are now affecting youtube-scrape as well?

**Comment by HermanFassett** [comment]
Thanks for the issue, it does appear that a change to YouTube is causing this issue. Sometimes the API still loads so I think the change has been incremental and still uses the old version in some cases. It appears an update will need to parse script tag from scraped url pre-load, I'll take a further look at it later.

**Comment by fightveryexplosion** [comment]
Thank you for looking into it!
I really appreciate your work on this library :)

**Comment by HermanFassett** [comment]
Started work on it, open pull request to develop with #19 if you want to check it out.

**Comment by HermanFassett** [comment]
PR #19 merged in development, PR #20 open to merge into master but needs more testing

**Comment by HermanFassett** [comment]
Changes merged to master with PR #20 and see deployed app returning results. Not extensively tested so please let me know if there are new issues resulting from the update.

**Comment by fightveryexplosion** [comment]
I'm getting results without fault now!! Thank you so much!
