### ISSUE TITLE
Heroku Application error

### ISSUE THREAD

**Issue by iamnotstatic** [HermanFassett/youtube-scrape#27]
I think the API is crashing can you help fix it, It's affecting my Bot

**Comment by HermanFassett** [comment]
My heroku site is online again, but I do see there are errors being thrown for contents undefined which may affect some calls.

In the future you should set up your own deploy of this since I use free hosting and it is not guaranteed to stay up.

**Comment by HermanFassett** [comment]
The secondary error being thrown should also be fixed, let me know if there are any more issues
