### ISSUE TITLE
Wrong video duration if over one hour

### ISSUE THREAD

**Issue by de666** [HermanFassett/youtube-scrape#3]
If the video duration is more than one hour, the reported video duration is only in the format `hour:minute` and not `hour:minute:seconds`

example query:
`http://youtube-scrape.herokuapp.com/api/search?q=onde%20del%20mare&page=1`

**Comment by HermanFassett** [comment]
Hey thanks for the info. Are people actually using this? I kind of forgot about it

**Comment by de666** [comment]
What do you mean with 

> Are people actually using this?

?

**Comment by HermanFassett** [comment]
Just wondering if the API is actively used.

**Comment by pulkitj79** [comment]
I am not sure about others. But I have found it very useful for a project. Can you please help me in deploying this to Heroku? I am a beginner on this.

**Comment by HermanFassett** [comment]
> I am not sure about others. But I have found it very useful for a project. Can you please help me in deploying this to Heroku? I am a beginner on this.

Won't go into it here, basically with Heroku CLI you can pretty much create and set a heroku app as just another git remote that you can push to as you would github and it automatically deploys if you set stuff up correctly.

**Comment by pulkitj79** [comment]
Thanks Herman, that will help me.

**Comment by de666** [comment]
> Just wondering if the API is actively used.

I think it is. Why it should not?
I think it is extremely useful.

**Comment by mohitchoudhary25** [comment]
Hey, I was trying to use this but I don't get any response. Do you know if this is still working ?

**Comment by pulkitj79** [comment]
Yeah this has worked for me.

**Comment by mohitchoudhary25** [comment]
I have a dataset of about 30,000 song titles for which I need to find relevant video titles. SO this scraper helps immensely. However, after 150 continuous hits, I start getting no response. Any idea why this happens @pulkitj79

**Comment by HermanFassett** [comment]
@mohitchoudhary25 if you hit the http://youtube-scrape.herokuapp.com then I'm only hosting it on a free account at heroku so it has limited daily usage. As I mentioned, you'll want to set up your own endpoint for reliable api.

**Comment by pulkitj79** [comment]
@mohitchoudhary25  I have also deployed at heroku on a different URL. You can deploy it locally too. And yes, as YouTube does the rate limitation, it stops working after 150-200 links. You need to wait for some time to start again. However, I am working on a similar project to find the relevant video titles for song titles. Let's connect to discuss more. Mail me at pulkitj@gmail.com

**Comment by HermanFassett** [comment]
Thanks for this issue, it should be fixed now
