### ISSUE TITLE
Regional search 

### ISSUE THREAD

**Issue by andrewstech** [HermanFassett/youtube-scrape#32]
Hello I was wondering if there was a way to change the region of the search due to region lock in different country's.

**Comment by HermanFassett** [comment]
Hmm not at this point. Would it be a query string parameter or a base url change? If it's either case, it shouldn't be too hard to implement

**Comment by andrewstech** [comment]
I would think it would be a parameter change.

On the YouTube website I can see a request with the following parameters " context: {client: {hl: "en", gl: "GB", visitorData: "CgtjZHhVRFBuelhZayjG5Jr8BQ%3D%3D",…},…},…}  " from this i am assuming en is language and GB is the country.

So I would say parameters are the way to go.

**Comment by fightveryexplosion** [comment]
I would also love to see this feature!

**Comment by YazeedAlKhalaf** [comment]
I just tried it with postman, another way to make it work!
add the `Accept-Language` header to the request when requesting a youtube page, I think we could implement something like this as a parameter when searching and passing it to the header when scraping. It will be a really cool idea.
I don't know about @andrewstech suggestion, cuz I didn't try it but yea.

Example:
```
Accept-Language: en-US,en;q=0.9 // this will show in english
// or
Accept-Language: ar-SA,ar;q=0.9 // this will show in arabic

**Comment by YazeedAlKhalaf** [comment]
Update, I have implemented my suggestion and it is in a PR right now #58
