### ISSUE TITLE
The scraper returns same result with different page number

### ISSUE THREAD

**Issue by FashionCStar** [HermanFassett/youtube-scrape#36]
https://www.youtube.com/results?q=angular&page=1
https://www.youtube.com/results?q=angular&page=2

Youtube returns the same result from the above 2 URLs

Due to your code, it should return different results, but on my side when I input search query in the youtube site search box and do the search, it doesn't show page parameter in the search result URL right?

I want to get a different result for every page number

**Comment by HermanFassett** [comment]
I think YouTube has been phasing out old page query so it no longer works. The official API appears to use pageTokens with results returning the nextPageToken and previousPageToken. I haven't been able to find anything that would work on the youtube site query side for pagination token yet. I can see that there is a continuationItemRenderer returned at the end of each page of results youtube loads and that contains a token and other data, but I'm not sure if we can use that externally or not.
