### ISSUE TITLE
Thumbnails urls are not correct 

### ISSUE THREAD

**Issue by MSZ991** [HermanFassett/youtube-scrape#5]
Thank you for this project.I would like to say that thumbnails urls are not correct.Only few top 2-3 urls are correct other results are undefined gif.
<img width="859" alt="Screen Shot 2019-06-28 at 10 11 54 AM" src="https://user-images.githubusercontent.com/14855029/60318804-d5ec9180-998d-11e9-8b2d-3eb669efcc6b.png">

**Comment by HermanFassett** [comment]
Thanks I'll take a look at it

**Comment by HermanFassett** [comment]
Thanks for making this issue, it should be fixed now

**Comment by MSZ991** [comment]
Hey! Is there any way we can get video id as well? Can you add that feature.It would be great.
Thanks

**Comment by HermanFassett** [comment]
> Hey! Is there any way we can get video id as well? Can you add that feature.It would be great.
> Thanks

Sure, should have video ids now
