### ISSUE TITLE
[QUESTION] Can I use this API with my application that might generate mass request

### ISSUE THREAD

**Issue by sudipghimire533** [HermanFassett/youtube-scrape#65]
I am planning to make a experimental service which requires search in high volume. Is it okay if I use your API for such application. The reason I am asking is if you are limited by dyno hours or not.

**Comment by HermanFassett** [comment]
Yeah my heroku deploy is limited to hours. Definitely recommend deploying to your own endpoint and make sure you test a lot because I know in the past youtube did some request limiting on IP though I haven't seen it recently.

**Comment by sudipghimire533** [comment]
Got it.
